/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vegatrader_market_journal_NativeJournal */

#ifndef _Included_com_vegatrader_market_journal_NativeJournal
#define _Included_com_vegatrader_market_journal_NativeJournal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    nativeAbiVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vegatrader_market_journal_NativeJournal_nativeAbiVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    initWriter
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_vegatrader_market_journal_NativeJournal_initWriter
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    append
 * Signature: (JIJJI[B)V
 */
JNIEXPORT void JNICALL Java_com_vegatrader_market_journal_NativeJournal_append
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jint, jbyteArray);

/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    closeWriter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vegatrader_market_journal_NativeJournal_closeWriter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    initReplay
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_vegatrader_market_journal_NativeJournal_initReplay
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    seek
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_vegatrader_market_journal_NativeJournal_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_vegatrader_market_journal_NativeJournal
 * Method:    closeReplay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vegatrader_market_journal_NativeJournal_closeReplay
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
